class Board:
    def __init__(self, *args):
        ...
    @property
    def legal_moves(self):
        return []
    @property
    def turn(self):
        ...
    def is_game_over(self):
        ...
    def is_checkmate(self):
        ...
    def is_stalemate(self):
        ...
    def has_insufficient_material(self, turn):
        ...